# Generated by Django 2.1.7 on 2019-03-27 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('student_class', models.CharField(max_length=20)),
            ],
        ),
    ]
